spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://database-2.cbomu2egqtut.ap-northeast-2.rds.amazonaws.com:3306/odangsadb
    username: root
    password: odangsa1234
  second-datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:~/test
    username: sa
    password:
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7