spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.cbomu2egqtut.ap-northeast-2.rds.amazonaws.com:3306/odangsadb
    username: root
    password: odangsa1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7


