spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7


